### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by mikemellor11** [chimo/grunt-fontello-svg#1]
Hey there, could you publish this to npm so that i can use in my project, i think this grunt task is extremely useful

**Comment by chimo** [comment]
Hi!
Sure, done: https://www.npmjs.com/package/grunt-fontello-svg

In case you aren't aware, you can add git repositories to your package.json dependencies too.
Ex:

```
  "dependencies": {
    "name": "git+https://github.com/username/project.git#branch_name"
  }
```

Cheers!

**Comment by mikemellor11** [comment]
I wasn't aware you could do that, thanks.
