### ISSUE TITLE
Update to latest fontello_svg

### ISSUE THREAD

**Issue by mikemellor11** [chimo/grunt-fontello-svg#2]
Hey i've added a new feature and fixed a bug in fontello-svg, could you update this package to point to the latest version - 0.5.0?

Thanks

**Comment by chimo** [comment]
Hey,
  Great changes! I've incorporated them in the dependency.

Let me know if that works.

**Comment by mikemellor11** [comment]
```
function fontelloSvg(configFile, outDirectory, opt, callback) {
  var config = require(path.resolve(configFile)),
    out = path.resolve(outDirectory),
    colors = opt.fillColors || {'black': '#000000'},
    backgroundUrlPath = opt.cssPath || '',
    **fileFormat = config.fileFormat || "{0}-{1}-{2}.svg",**
    glyphs = allGlyphs(config.glyphs, colors, fileFormat);
```
could you change this line 

fileFormat = **config**.fileFormat || "{0}-{1}-{2}.svg",

to

fileFormat = **opt**.fileFormat || "{0}-{1}-{2}.svg",

**Comment by chimo** [comment]
Yep, done!

Happy new year to you as well :)

**Comment by mikemellor11** [comment]
Perfect thank you.
